apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: crvx-app
  name: crvx-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crvx-app
  template:
    metadata:
      labels:
        app: crvx-app
    spec:
      containers:
        - image: sundowndev/website@sha256:af62dd7757df9e84d072bbcd26a8da6a899d9ca4b6525b074372544ef5b39da3
          name: crvx-app
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
