apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: crvx-app
  name: crvx-app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: crvx-app
  template:
    metadata:
      labels:
        app: crvx-app
    spec:
      containers:
        - image: sundowndev/website@sha256:27d3c607d85139d84bd8010e567fb886875cc6af5d71439f0f878c02a807fe04
          name: crvx-app
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
