apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: crvx-app
  name: crvx-app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: crvx-app
  template:
    metadata:
      labels:
        app: crvx-app
    spec:
      containers:
        - image: sundowndev/website@sha256:4b57fd1e17f6ad486c01cc54560097496af17cbaef593427bb328234a3d95ca9
          name: crvx-app
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
