apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: crvx-app
  name: crvx-app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: crvx-app
  template:
    metadata:
      labels:
        app: crvx-app
    spec:
      containers:
        - image: sundowndev/website@sha256:8ed186503e55c45104402203a798af748a3cf8fa39d5563697e8784e92698c01
          name: crvx-app
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
