apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: crvx-app
  name: crvx-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crvx-app
  template:
    metadata:
      labels:
        app: crvx-app
    spec:
      containers:
        - image: sundowndev/website@sha256:d0ce660a63a3a5b2645347ff0e184fdb6e8fbe45135912ee8bcd5546a3a6a0cf
          name: crvx-app
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
