apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: crvx-app
  name: crvx-app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: crvx-app
  template:
    metadata:
      labels:
        app: crvx-app
    spec:
      containers:
        - image: sundowndev/website@sha256:f7f5f022203d71fb4ef76ca106f933ded9d2b47f6871ddfa1fdc8a1241a53af1
          name: crvx-app
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
