apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: crvx-app
  name: crvx-app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: crvx-app
  template:
    metadata:
      labels:
        app: crvx-app
    spec:
      containers:
        - image: sundowndev/website@sha256:6e7d40cabfae33bc5846d7b19daff396111cc3ab873faa90357ff83ffe44f05e
          name: crvx-app
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
