apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: crvx-app
  name: crvx-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crvx-app
  template:
    metadata:
      labels:
        app: crvx-app
    spec:
      containers:
        - image: sundowndev/website@sha256:36e7386fa18798fde1e6f26aa60cc5253fabb8bbba3d2c88082c2f42fa556b7f
          name: crvx-app
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
