apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: crvx-app
  name: crvx-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crvx-app
  template:
    metadata:
      labels:
        app: crvx-app
    spec:
      containers:
        - image: sundowndev/website@sha256:b8b44d5d3fe35f770e3f294bc8db543f7aeabc940630d44c33150d65c64d40d6
          name: crvx-app
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
